openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Rights Service
  description: |
    This service allows reading crawled water right information via an API for
    easier access than the official Cadenza software.

    *Please note that the data output by the service is licensed under the*
    Datenlizenz Deutschland – Namensnennung – Version 2.0 *and usage of the
    data output via the API is still subject to this license. [Read more]*

    [Read more]: www.nlwkn.niedersachsen.de/opendata

servers:
  - url: /api/water-rights/v1/
    description: WISdoM Platform

  - url: http://localhost:8000/v1/
    description: Local Development Server

components:
  schemas:
    LegalDepartment:  
      type: string
      enum: [A,B,C,D,E,F,K,L]
      description: |
        The legal department the usage location is associated with

        | **Letter** | **Description**                                                 |
        | :--------- | :-------------------------------------------------------------- |
        | A          | Withdrawal of water or solid substances from surface waters     |
        | B          | Introduction and discharge of substances into surface waters    |
        | C          | Damming and lowering of surface waters                          |
        | D          | Other impacts on surface waters                                 |
        | E          | Withdrawal, extraction, conveyance and discharge of groundwater |
        | F          | Other uses and impacts on groundwater                           |
        | K          | Compulsory rights                                               |
        | L          | Fishing Rights                                                  |

    Quantity:
      type: object
      properties:
        value:
          type: number
        unit:
          type: string

    Rate:
      allOf:
        - $ref: '#/components/schemas/Quantity'
        - properties:
            per:
              type: number
              minimum: 0
              description: interval duration in microseconds

    LandRecord:
      type: object
      properties:
        district:
          type: string
        field:
          type: integer
        fallback:
          type: string

    NumericKeyedName:
      type: object
      properties:
        key:
          type: number
        value:
          type: string

    UsageLocation:
      type: object
      required:
        - id
        - legalDepartment
      properties:
        id:
          type: integer
          description: |
            Database Identifier of the usage location
        no:
          type: integer
          description: |
            Cadenza Identifier of the usage location
        serial:
          type: string
          description: |
            Enumeration for the usage location within a water right
        waterRight:
          type: integer
          description: |
            The Water Right this usage location is associated with
        legalDepartment:
          $ref: '#/components/schemas/LegalDepartment'
        active:
          type: boolean
          description: |
            The state of the usage location
        real:
          type: boolean
          description: |
            Indicates if the usage location actually exists or is just a
            virtual location used to group other usage locations together
        name:
          type: string
          description: |
            The name of the usage location or another descriptor
        legalPurpose:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: string
          description: |
            The legal purpose under which the water right has been
            granted
        mapExcerpt:
          allOf:
            - description: an area on a topological map using a 1:25000 scale
            - $ref: '#/components/schemas/NumericKeyedName'
        municipalArea:
          allOf:
            - description: |
                the ARS and the name of the municipal the usage location is 
                located in
            - $ref: '#/components/schemas/NumericKeyedName'
        county:
          type: string
          description: |
            The county the usage location is located in
        landRecord:
          $ref: '#/components/schemas/LandRecord'
        plot:
          type: string
        maintenanceAssociation:
          allOf:
            - description: |
                Information about the (legal) person reesponsible for 
                maintaining the usage location
            - $ref: '#/components/schemas/NumericKeyedName'
        euSurveyArea:
          allOf:
            - description: |
                A EU-wide identification of the area the usage location is in
            - $ref: '#/components/schemas/NumericKeyedName'
        catchmentAreaCode:
          allOf:
            - description: |
                Further information about the location of the usage area
            - $ref: '#/components/schemas/NumericKeyedName'
        regulationCitation:
          type: string
          description: |
            A citation from the regulation about the water rights
        withdrawalRates:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
        pumpingRates:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
        injectionRates:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
        wasteWaterFlowVolume:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
        riverBasin:
          type: string
          description: |
            Information about the river that is used at the location
        groundwaterBody:
          type: string
          description: |
            Information about the groundwater body used at that location
        waterBody:
          type: string
          description: |
            Information about the surface water body used at the location
        floodArea:
          type: string
          description: |
            Information about the flood area that is in the usage locations
            vicinity
        waterProtectionArea:
          type: string
          description: |
            Information about a water protection area the usage location is
            located in
        damTagetLevels:
          type: object
          properties:
            default:
              $ref: '#/components/schemas/Quantity'
            steady:
              $ref: '#/components/schemas/Quantity'
            max:
              $ref: '#/components/schemas/Quantity'
        fluidDischarge:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
        rainSupplement:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
        irrigationArea:
          $ref: '#/components/schemas/Quantity'
        phValues:
          type: object
        injectionLimits:
          type: array
          items:
            allOf:
              - type: object
                properties:
                  substance:
                    type: string
              - $ref: '#/components/schemas/Quantity'
        location:
          type: object
          description: The GeoJSON representation of the usage locations location

    WaterRight:
      type: object
      properties:
        id:
          type: integer
          description: |
            A Database-generated id
        waterRightNumber:
          type: integer
          description: |
            An identification issued by the NLWKN
        holder:
          type: string
        validFrom:
          type: string
          format: datetime
        validUntil:
          type: string
          format: datetime
        status:
          type: string
        legalTitle:
          type: string
        waterAuthority:
          type: string
        registeringAuthority:
          type: string
        grantingAuthority:
          type: string
        initiallyGranted:
          type: string
          format: date
        lastChange:
          type: string
          format: date
        fileReference:
          type: string
        externalIdentifier:
          type: string
        subject:
          type: string
        address:
          type: string
        legalDepartments:
          type: array
          items:
            $ref: '#/components/schemas/LegalDepartment'
        annotation:
          type: string

paths:
  /:
    get:
      summary: Usage Locations
      responses:
        "200":
          description: (Filtered) Usage Locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsageLocation'

  /details/{water-right-id}:
    parameters:
      - in: path
        name: water-right-id
        required: true
        schema:
          type: string

    get:
      description: Water Right Details
      responses:
        "200":
          description: Water Right Details
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  water-right:
                    $ref: '#/components/schemas/WaterRight'
                  usage-locations:
                    type: array
                    items:
                      $ref: '#/components/schemas/UsageLocation'
              encoding:
                water-right:
                  contentType: application/json
                usage-location:
                  contentType: application/json