name: "CodeQL"
on:
  pull_request:
    branches:
      - main
      - dev
  push:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - go
        build-tag:
          - docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize latest stable Go Version
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality

      - name: Build Service Executable
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis — Docker
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}:docker"
        env:
          GOFLAGS: "-tags=docker"

      - name: Perform CodeQL Analysis — Local Development
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}:local"