name: docker
on:
  workflow_dispatch:
  push:
    branches: '**'
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - id: checkout
        name: Checkout Build Sources
        uses: actions/checkout@v4

      - uses: wisdom-oss/actions/docker-build/multiplatform/build@main
        name: 
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          cache-key: go-cache-${{ github.repository_id }}
          target-platform: ${{ matrix.platforms }}
          cache-path: go-mod-build
          cache-map: |
            {
              "go-mod-build": "/root/.cache/go-build"
            }

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.event_name != 'pull_request'
    steps:
      - uses: wisdom-oss/actions/docker-build/multiplatform/merge@main
        name: 
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}